# ------------------------------------------------------------
# 🎵 Spotify Integration Module
# Handles Spotify API authentication & token management using Spotipy
# ------------------------------------------------------------

import os
from pathlib import Path
from dotenv import load_dotenv #Load your Spotify credentials from .env safely
import streamlit as st
import spotipy #Spotify API client
from spotipy.oauth2 import SpotifyOAuth, SpotifyOauthError #Handles Spotify login
import time  #For token expiration handling

# ------------------------------------------------------------
# 🔧 Load environment variables
# ------------------------------------------------------------
env_path = Path(__file__).parent.parent / ".env" # Adjust path as needed
load_dotenv(dotenv_path=env_path) 

SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID", "b0e32a2636ac44a699844f06637a573e").strip()
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "63885723876f4a25a247fb294a5e92a8").strip()
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI", "http://localhost:8502/callback").strip()

# ------------------------------------------------------------
# 🚨 Validate credentials
# ------------------------------------------------------------
if not all([SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REDIRECT_URI]): 
    st.error("Missing Spotify credentials. Please update `.env` or hardcode values.")
    st.stop()

# ------------------------------------------------------------
# ⚙️ Spotify OAuth configuration
# ------------------------------------------------------------
def get_spotify_oauth(): # Configure Spotify OAuth
    return SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        redirect_uri=SPOTIFY_REDIRECT_URI,
        scope="playlist-modify-public playlist-modify-private user-library-read",
        cache_path=".cache",
        show_dialog=True
    )

# ------------------------------------------------------------
# 🔄 Refresh token automatically
# ------------------------------------------------------------
def refresh_spotify_token(): # Refresh Spotify token if expired
    token_info = st.session_state.get("spotify_token")
    if not token_info:
        return None

    now = int(time.time())
    if token_info["expires_at"] - now < 60:
        sp_oauth = get_spotify_oauth()
        try:
            token_info = sp_oauth.refresh_access_token(token_info["refresh_token"])
            st.session_state.spotify_token = token_info
            st.success("🔁 Spotify token refreshed successfully.")
        except SpotifyOauthError as e:
            st.error(f"Failed to refresh token: {e}")
            st.session_state.spotify_token = None
            return None
    return token_info

# ------------------------------------------------------------
# 🎟️ Spotify Authentication Flow
# ------------------------------------------------------------
def spotify_authenticate(): # Authenticate user with Spotify
    if "spotify_token" not in st.session_state:
        st.session_state.spotify_token = None

    sp_oauth = get_spotify_oauth()

    # If user hasn’t authenticated yet
    if not st.session_state.spotify_token:
        auth_url = sp_oauth.get_authorize_url()
        st.markdown(f"👉 [Click here to authenticate with Spotify]({auth_url})")
        st.info("After logging in, you’ll be redirected back to the app automatically.")
        return None

    # Refresh token if expired
    token_info = refresh_spotify_token()
    if not token_info:
        return None

    # Create Spotify client
    try:
        sp = spotipy.Spotify(auth=token_info["access_token"])
        user = sp.current_user()
        st.success(f"🎧 Logged in as: **{user['display_name']}**")
        return sp
    except Exception as e:
        st.error(f"Spotify authentication failed: {e}")
        st.session_state.spotify_token = None
        return None

# ------------------------------------------------------------
# 🎶 Helper: Check if playlist exists
# ------------------------------------------------------------
def get_playlist_id(sp, playlist_name): 
    user_id = sp.current_user()["id"]
    playlists = sp.user_playlists(user_id)
    for playlist in playlists["items"]:
        if playlist["name"] == playlist_name:
            return playlist["id"]
    return None

# ------------------------------------------------------------
# 🎶 Helper: Create playlist
# ------------------------------------------------------------
def create_playlist(sp, playlist_name, public=False, description="Generated by Streamlit App"):
    user_id = sp.current_user()["id"]
    playlist = sp.user_playlist_create(user=user_id, name=playlist_name, public=public, description=description)
    return playlist["id"]

# ------------------------------------------------------------
# 🎶 Helper: Add tracks to playlist
# ------------------------------------------------------------
def add_tracks_to_playlist(sp, playlist_name, track_ids):
    playlist_id = get_playlist_id(sp, playlist_name)
    if not playlist_id:
        playlist_id = create_playlist(sp, playlist_name)
        st.success(f"🎶 Playlist '{playlist_name}' created.")

    if track_ids:
        sp.playlist_add_items(playlist_id, track_ids)
        st.success(f"✅ Added {len(track_ids)} tracks to '{playlist_name}'")
    else:
        st.warning("⚠️ No track IDs provided to add.")

# ------------------------------------------------------------
# 🎶 Helper: Get Spotify recommendations
# ------------------------------------------------------------
def get_spotify_recommendations(mood, limit=10):
    sp = spotify_authenticate()
    if not sp:
        return []

    # Map mood to seed genres or tracks
    mood_seeds = { 
        'happy': {'seed_genres': ['pop'], 'target_valence': 0.8, 'target_energy': 0.8},
        'sad': {'seed_genres': ['indie'], 'target_valence': 0.2, 'target_energy': 0.3},
        'energetic': {'seed_genres': ['rock'], 'target_valence': 0.7, 'target_energy': 0.9},
        'calm': {'seed_genres': ['ambient'], 'target_valence': 0.5, 'target_energy': 0.2}
    } 

    seeds = mood_seeds.get(mood.lower(), mood_seeds['happy'])

    try:
        recommendations = sp.recommendations(
            seed_genres=seeds['seed_genres'],
            limit=limit,
            target_valence=seeds['target_valence'],
            target_energy=seeds['target_energy']
        )
        tracks = []
        for track in recommendations['tracks']:
            tracks.append({
                'name': track['name'],
                'artist': track['artists'][0]['name'],
                'url': track['external_urls']['spotify']
            })
        return tracks
    except Exception as e:
        st.error(f"Error getting recommendations: {e}")
        return []

# ------------------------------------------------------------
# 🎶 Helper: Add track to playlist (single track or list)
# ------------------------------------------------------------
def add_track_to_playlist(mood, track_uris):
    sp = spotify_authenticate()
    if not sp:
        return

    playlist_name = f"{mood.capitalize()} Mood Playlist"
    playlist_id = get_playlist_id(sp, playlist_name)
    if not playlist_id:
        playlist_id = create_playlist(sp, playlist_name)

    if isinstance(track_uris, str):
        track_uris = [track_uris]

    if track_uris:
        sp.playlist_add_items(playlist_id, track_uris)
        st.success(f"✅ Added {len(track_uris)} tracks to '{playlist_name}'")
    else:
        st.warning("⚠️ No track URIs provided to add.")

# ------------------------------------------------------------
# 🎶 Helper: Create or get playlist
# ------------------------------------------------------------
def create_or_get_playlist(mood):
    sp = spotify_authenticate()
    if not sp:
        return None

    playlist_name = f"{mood.capitalize()} Mood Playlist"
    playlist_id = get_playlist_id(sp, playlist_name)
    if not playlist_id:
        playlist_id = create_playlist(sp, playlist_name)
    return playlist_id

# ------------------------------------------------------------
# 🎶 Helper: Get playlist tracks
# ------------------------------------------------------------
def get_playlist_tracks(mood):
    sp = spotify_authenticate()
    if not sp:
        return []

    playlist_id = create_or_get_playlist(mood)
    if not playlist_id:
        return []

    try:
        results = sp.playlist_tracks(playlist_id)
        tracks = []
        for item in results['items']:
            track = item['track']
            tracks.append({
                'name': track['name'],
                'artist': track['artists'][0]['name'],
                'url': track['external_urls']['spotify']
            })
        return tracks
    except Exception as e:
        st.error(f"Error getting playlist tracks: {e}")
        return []

# ------------------------------------------------------------
# 🎶 Standalone test (optional)
# ------------------------------------------------------------
if __name__ == "__main__":
    st.title("Spotify Authentication Test")
    spotify_client = spotify_authenticate()
    if spotify_client:
        st.write("✅ Spotify client is active and ready.")

        # Example: Add sample tracks
        example_tracks = [
            "spotify:track:4uLU6hMCjMI75M1A2tKUQC",  # Replace with your own tracks
        ]
        add_tracks_to_playlist(spotify_client, "My Test Playlist", example_tracks)
